-- CREATE DATABASE CONVERSATION_APP

GO
USE CONVERSATION_APP

CREATE TABLE CONVERSATIONn (
    ID INT PRIMARY KEY IDENTITY,
    CONVERSATION_NAME NVARCHAR(MAX),
    CONTENT NVARCHAR(MAX),
    DURATION TIME,
    AUDIO_STATUS VARCHAR(100),
    CREATED_DATE DATETIME,
    GROUP_ID INT,
    USER_ID INT,
)

CREATE TABLE CONVERSAITON_GROUP (
    ID INT PRIMARY KEY IDENTITY,
    GROUP_NAME NVARCHAR(MAX),
    CONVERSATION_DESCRIPTION NVARCHAR(MAX),
    GROUP_LOCATION NVARCHAR(MAX),
)

CREATE TABLE TRASH(
    ID INT PRIMARY KEY IDENTITY,
    CONVERSATION_ID INT,
    REMOVED_DATETIME DATETIME,
)

CREATE TABLE USER(
    ID INT PRIMARY KEY IDENTITY,
    USER_NAME VARCHAR(MAX),
    HASH_PASSWORD NVARCHAR(MAX),
    DISPLAY_USR_NAME NVARCHAR(MAX),
    LANGUAGE_ID VARCHAR(MAX),
    DELETE_DURATION DATETIME,
    DELETE_MANUALLY BIT, -- 1 = TRUE; 0 = FASLE
)

CREATE TABLE USER_LANGUAGE(
    ID VARCHAR(MAX) PRIMARY KEY,
    USER_LANGUAGE VARCHAR(MAX),
)





CREATE TABLE ROLE(
    ID INT PRIMARY KEY IDENTITY,
    ROLE_NAME VARCHAR(MAX),
    ROLE_DESCRIPTION NVARCHAR(MAX),
)

CREATE TABLE PERMISSION(
    ID INT PRIMARY KEY IDENTITY,
    PERMISSION_NAME VARCHAR(MAX),
    PERMISSION_DESCRIPTION NVARCHAR(MAX),
)

CREATE TABLE USER_ROLE(
    USER_ID INT,
    ROLE_ID INT,    
    PRIMARY KEY(USER_ID, ROLE_ID),
)

CREATE TABLE ROLE_PERMISSTION(
    ROLE_ID INT,
    PERMISSION_ID INT, 
    PRIMARY KEY(ROLE_ID, PERMISSION_ID),
)

ALTER TABLE CONVERSATIONn ADD CONSTRAINT fk_group FOREIGN KEY (GROUP_ID) REFERENCES CONVERSAITON_GROUP(ID)
ALTER TABLE CONVERSATIONn ADD CONSTRAINT fk_user FOREIGN KEY (USER_ID) REFERENCES USER(ID)
ALTER TABLE TRASH ADD CONSTRAINT fk_conversation FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONn (ID)

ALTER TABLE USER ADD CONSTRAINT fk_user_language FOREIGN KEY (LANGUAGE_ID) REFERENCES USER_LANGUAGE (ID)

ALTER TABLE USER_ROLE ADD CONSTRAINT fk_user_role_userid FOREIGN KEY (USER_ID) REFERENCES USER (ID)
ALTER TABLE USER_ROLE ADD CONSTRAINT fk_user_role_roleid FOREIGN KEY (ROLE_ID) REFERENCES  USER_ROLE(ID)

ALTER TABLE ROLE_PERMISSTION ADD CONSTRAINT fk_role_permission_roleid FOREIGN KEY (ROLE_ID) REFERENCES  USER_ROLE(ID)
ALTER TABLE ROLE_PERMISSTION ADD CONSTRAINT fk_role_permission_permission FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)



SELECT USER_NAME, USER_LANGUAGE, DELETE_DURATION, DELETE_MANUALLY FROM USER INNER JOIN USER_LANGUAGE ON  USER.USER_LANGUAGE = USER_LANGUAGE.ID
    WHERE USER_ID = user
    OFFSET m ROWS FETCH NEXT 6 ROW ONLY 


DECLARE @username VARCHAR(MAX) = 'username_to_lookup';
SELECT DISTINCT P.PERMISSION_NAME, P.PERMISSION_DESCRIPTION 
    FROM USER A 
        JOIN USER_ROLE UR ON A.ID = UR.USER_ID 
        JOIN ROLE_PERMISSION RP ON UR.ROLE_ID = RP.ROLE_ID 
        JOIN PERMISSION P ON RP.PERMISSION_ID = P.ID 
    WHERE A.USER_NAME = @username;
